subjects:
  fused.track:
    pubs: [fusion_ae]
    subs: [advisory_ae, roe_ae]
    labels: [CUI]

  roe.result:
    pubs: [roe_ae]
    subs: [advisory_ae, sub_ae]

  classified.data:
    pubs: []
    subs: []
    labels: [SECRET]

  fusion.topic:
    pubs: [fusion_ae]
    subs: [test_sse_ae]
    labels: [default]

  hello.world:
    pubs: [pub_ae]
    subs: [sub_ae]

  sdk.test:
    pubs: [ sdk_test_ae ]
    subs: [ sdk_test_ae ]
    labels: [ default ]

  sdk.test.reply:
    pubs: [ sdk_test_ae ]
    subs: [ sdk_test_ae ]
    labels: [ default ]

roles:
  subscriber: {}